<!DOCTYPE html>
<html>

<head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta charset="utf-8">
    <title>Projects Summary</title>
    <link rel=" stylesheet" href="<?php echo base_url('assets/css/report-pdf.css') ?>"">

</head>
<?php
if (!empty($report_date)) {
    $summ =   _l('historical');
 } else{
    $summ =   _l('as_on_date');;
 }
?>
<body>
<h1 class="text-center" style=" text-align:center; font-size:26px;"><?php echo get_option('companyname'); ?></h1>
   
    <table class="no-bdr">
        <tr>
            <td class="text-left" colspan="9">
                <span class="date">Date: <?php echo date('d-m-Y H:i'); ?></span><br>
                <span class="generated">Generated By: <?php echo $GLOBALS['current_user']->firstname . ", " . $GLOBALS['current_user']->role_name. ", " . $GLOBALS['current_user']->organisation; ?></span>
                <?php if (!($GLOBALS['current_user']->role_slug_url == "ae-global" && empty($tableParams['area_name']))) { ?>
                    <br> <span class="generated"><?php echo str_replace("/", ",", get_staff_location('plain')); ?></span>
                <?php } ?>
                <p class="generated">In case of any queries, please contact support at <?php echo get_option('email_signature'); ?></p>
            </td>
        </tr>

    </table>
    <h2 class="text-center" style=" text-align:center;">Summary of India<?php echo (!empty($tableParams['area_name'])) ? ", " . $tableParams['area_name'] : ''; ?></h2>
    <span class="generated"><?php echo $summ;  ?></span><hr>
    <table border="1">
        <thead>
            <tr>
                <th border="0"></th>
                <th><?php echo _l('New'); ?></th>
                <th class="escalated">Delayed</th>
                <th class="wip">In Progress</th>
                <th class="closed"><?php echo _l('Closed'); ?></th>
                <th class="wip">Rejected</th>
                <th class="wip">Unassigned</th>
                <th class="wip">Frozen</th>
                <th class="total-column"><?php echo _l('Total'); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td border="0"></td>
                <td><?php echo (!empty($chart_data['new'])) ? $chart_data['new'] : '0'; ?></td>
                <td><?php echo (!empty($chart_data['escalated'])) ? $chart_data['escalated'] : '0';  ?></td>
                <td><?php echo (!empty($chart_data['wip'])) ? $chart_data['wip'] : '0'; ?></td>
                <td><?php echo (!empty($chart_data['close'])) ? $chart_data['close'] : '0';  ?></td>
                <td><?php echo (!empty($chart_data['reject'])) ? $chart_data['reject'] : '0'; ?></td>
                <td><?php echo (!empty($chart_data['unassign'])) ? $chart_data['unassign'] : '0'; ?></td>
                <td><?php echo (!empty($chart_data['frozen'])) ? $chart_data['frozen'] : '0'; ?></td>
                <td><?php echo (!empty($chart_data['total'])) ? $chart_data['total'] : '0'; ?></td>

                <!-- <?php //foreach ($chart_data as $val) { print_r($chart_data); exit;
                        ?>
                    <td><?php //echo (!empty($val)) ? $val : '0'; 
                        ?></td>
                <?php //} 
                ?> -->
            </tr>
        </tbody>
    </table>
    <h2 class="text-center"></h2>
    <h2 class="text-center"></h2>
    <?php if ($GLOBALS['current_user']->role_slug_url == "ae-global" && empty($tableParams['area_name'])) { ?>
        <table border="1">
            <thead>
                <tr bgcolor="#CCCCCC">
                    <th class="text-left"><?php echo _l('State'); ?></th>
                    <th><?php echo _l('New'); ?></th>
                    <th class="escalated">Delayed</th>
                    <th class="wip">In Progress</th>
                    <th class="closed"><?php echo _l('Closed'); ?></th>
                    <th class="wip">Rejected</th>
                    <th class="wip">Unassigned</th>
                    <th class="wip">Frozen</th>
                    <th class="total-column"><?php echo _l('Total'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($statuses as $val) {
                    if (!empty($val['name'])) {
                ?>
                        <tr>
                            <td class="text-left"><?php echo (!empty($val['name'])) ? $val['name'] : ''; ?></td>
                            <td><?php echo (!empty($val['new'])) ? $val['new'] : '0'; ?></td>
                            <td><?php echo (!empty($val['escalated'])) ? $val['escalated'] : '0';  ?></td>
                            <td><?php echo (!empty($val['wip'])) ? $val['wip'] : '0'; ?></td>
                            <td><?php echo (!empty($val['close'])) ? $val['close'] : '0';  ?></td>
                            <td><?php echo (!empty($val['rejected'])) ? $val['rejected'] : '0'; ?></td>
                            <td><?php echo (!empty($val['unassigned'])) ? $val['unassigned'] : '0'; ?></td>
                            <td><?php echo (!empty($val['frozen'])) ? $val['frozen'] : '0'; ?></td>
                            <td><?php echo (!empty($val['total'])) ? $val['total'] : '0'; ?></td>
                        </tr>
                <?php }
                } ?>
            </tbody>
        </table>
    <?php } ?>
    <h2 class="text-center"></h2>
    <table border="1">
        <thead>
            <tr>
                <th class="text-left"><?php echo _l('State/City/Corp.'); ?></th>
                <th><?php echo _l('New'); ?></th>
                <th class="escalated">Delayed</th>
                <th class="wip">In Progress</th>
                <th class="closed"><?php echo _l('Closed'); ?></th>
                <th class="wip">Rejected</th>
                <th class="wip">Unassigned</th>
                <th class="wip">Frozen</th>
                <th class="total-column"><?php echo _l('Total'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($statuses as $val) {
                if (!empty($val['name'])) {
            ?>
                    <tr class="region" bgcolor="#dddddd" style="font-weight:bold;">
                        <td class="text-left"><?php echo (!empty($val['name'])) ? $val['name'] : ''; ?></td>
                        <td><?php echo (!empty($val['new'])) ? $val['new'] : '0'; ?></td>
                        <td><?php echo (!empty($val['escalated'])) ? $val['escalated'] : '0';  ?></td>
                        <td><?php echo (!empty($val['wip'])) ? $val['wip'] : '0'; ?></td>
                        <td><?php echo (!empty($val['close'])) ? $val['close'] : '0';  ?></td>
                        <td><?php echo (!empty($val['rejected'])) ? $val['rejected'] : '0'; ?></td>
                        <td><?php echo (!empty($val['unassigned'])) ? $val['unassigned'] : '0'; ?></td>
                        <td><?php echo (!empty($val['frozen'])) ? $val['frozen'] : '0'; ?></td>
                        <td><?php echo (!empty($val['total'])) ? $val['total'] : '0'; ?></td>
                    </tr>
                    <?php if (!empty($val["region_status"])) {
                        foreach ($val["region_status"] as $status) { ?>
                            <tr class="" style="font-weight:bold;">
                                <td class="text-left"><?php echo $status["region_name"] ?></td>
                                <td><?php echo (!empty($status['new'])) ? $status['new'] : '0'; ?></td>
                                <td><?php echo (!empty($status['escalated'])) ? $status['escalated'] : '0';  ?></td>
                                <td><?php echo (!empty($status['wip'])) ? $status['wip'] : '0'; ?></td>
                                <td><?php echo (!empty($status['close'])) ? $status['close'] : '0';  ?></td>
                                <td><?php echo (!empty($status['rejected'])) ? $status['rejected'] : '0'; ?></td>
                                <td><?php echo (!empty($status['unassigned'])) ? $status['unassigned'] : '0'; ?></td>
                                <td><?php echo (!empty($status['frozen'])) ? $status['frozen'] : '0'; ?></td>
                                <td><?php echo (!empty($status['total'])) ? $status['total'] : '0'; ?></td>
                            </tr>

                            <?php if (!empty($status["sub_region_status"])) {
                                foreach ($status["sub_region_status"] as $sub_status) { ?>
                                    <tr class="subregion">
                                        <td class="text-left" style="padding-left:10px;">&nbsp;&nbsp;- <?php echo $sub_status["sub_region_name"] ?></td>
                                        <td><?php echo (!empty($sub_status['new'])) ? $sub_status['new'] : '0'; ?></td>
                                        <td><?php echo (!empty($sub_status['escalated'])) ? $sub_status['escalated'] : '0';  ?></td>
                                        <td><?php echo (!empty($sub_status['wip'])) ? $sub_status['wip'] : '0'; ?></td>
                                        <td><?php echo (!empty($sub_status['close'])) ? $sub_status['close'] : '0';  ?></td>
                                        <td><?php echo (!empty($sub_status['rejected'])) ? $sub_status['rejected'] : '0'; ?></td>
                                        <td><?php echo (!empty($sub_status['unassigned'])) ? $sub_status['unassigned'] : '0'; ?></td>
                                        <td><?php echo (!empty($sub_status['frozen'])) ? $sub_status['frozen'] : '0'; ?></td>
                                        <td><?php echo (!empty($sub_status['total'])) ? $sub_status['total'] : '0'; ?></td>
                                    </tr>

                                <?php } ?>

                            <?php } ?>
                    <?php }
                    } ?>
            <?php }
            } ?>
        </tbody>


    </table>
    <h2 class="text-center"></h2>
    <?php echo $html; ?>
    </body>

</html>