<!DOCTYPE html>
<html>

<head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta charset="utf-8">
    <title>ATR Summary</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel=" stylesheet" href="<?php echo base_url('assets/css/report-pdf.css?v='.time()) ?>">


</head>
<body>


<?php

$full_name = !empty($GLOBALS['current_user']->full_name) ? $GLOBALS['current_user']->full_name : '';
$role_name = !empty($GLOBALS['current_user']->role_name) ? $GLOBALS['current_user']->role_name : '';
$organisation = !empty($GLOBALS['current_user']->organisation) ? $GLOBALS['current_user']->organisation : '';
if (!empty($report_date)) {
    $summ =   _l('historical');
 } else{
    $summ =   _l('as_on_date');;
 }
?>
<table class=" header">
    <tr>
        <td class="text-left" width="75">
            <!-- <img src="<?php //echo //base_url('assets/images/cpcb-pdf-logo.png') ?>" alt=""> -->
            <?php if(!empty(get_logo('company_logo'))){ ?>
                <img src="<?php echo base_url(get_logo('company_logo')); ?>" alt="" style="width: 75px;height: 55px;">
            <?php } ?>
        </td>
        <td class="text-center">
            <h1><?php echo get_option('companyname'); ?></h1>

        </td>
        <td class="text-right" width="75">
            <?php if(!empty(get_area_logo())){ ?>
                <img src="<?php echo base_url(get_area_logo()); ?>" alt="" style="width: 75px;height: 55px;">
            <?php } ?>
        </td>
    </tr>
    </table>
    <table class="no-bdr">
        <tr>
            <td style="text-align:left;">
                <span class="date">Date: <?php echo date('d-m-Y H:i'); ?></span>
                <span class="generated">Generated by: <?php echo $full_name . ", " . $role_name. ", " . $organisation; ?></span>
                <span class="generated"><?php echo str_replace("/", ",", get_staff_location('plain')); ?></span>
                <span class="generated">In case of any queries, please contact support at <a href="mailto:<?php echo get_option('email_signature'); ?>"><?php echo get_option('email_signature'); ?></a></span>
            </td>
        </tr>
    </table>
    <h2 class="text-center">ATR Summary</h2>
     <span class="generated mB5"><?php echo $summ;  ?></span>
    </br>     
    <table class="">
<thead>
    <tr>
        <th><?php echo _l('New'); ?></th>
        <th><?php echo _l('Delayed'); ?></th>
        <th><?php echo _l('In Progress'); ?></th>
        <th><?php echo _l('Closed'); ?></th>
        <th><?php echo _l('Referred'); ?></th>
        <th><?php echo _l('Unassigned'); ?></th>
        <th><?php echo _l('Frozen'); ?></th>
        <th><?php echo _l('Total'); ?></th>
    </tr>
</thead>
<tbody>
    <?php foreach ($totals as $val) {
        $close =  (!empty($val['close'])) ? $val['close'] : '0';
        $escalated =  (!empty($val['escalated'])) ? $val['escalated'] : '0';
        $wip =  (!empty($val['wip'])) ? $val['wip'] : '0';
        $new =  (!empty($val['new'])) ? $val['new'] : '0';
        $reject =  (!empty($val['reject'])) ? $val['reject'] : '0';
        $unassign =  (!empty($val['unassign'])) ? $val['unassign'] : '0';
        $frozen =  (!empty($val['frozen'])) ? $val['frozen'] : '0';
        $total = $close + $escalated + $wip + $new + $reject + $unassign + $frozen ;
        ?>

        <tr>
            <td><?php echo $new ?></td>
            <td><?php echo $escalated  ?></td>
            <td><?php echo $wip ?></td>
            <td><?php echo $close  ?></td>
            <td><?php echo $reject  ?></td>
            <td><?php echo $unassign  ?></td>
            <td><?php echo $frozen  ?></td>
            <td><?php echo $total; ?></td>
        </tr>
    <?php } ?>
</tbody>
</table>
    <hr class="hr-panel-heading" />
    <table class="">

    <thead>
        <tr>
            <th><?php echo _l('Action Items'); ?></th>
            <th><?php echo _l('New'); ?></th>
            <th><?php echo _l('Delayed'); ?></th>
            <th><?php echo _l('In Progress'); ?></th>
            <th><?php echo _l('Closed'); ?></th>
            <th><?php echo _l('Referred'); ?></th>
            <th><?php echo _l('Unassigned'); ?></th>
            <th><?php echo _l('Frozen'); ?></th>
            <th><?php echo _l('Total'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($statuses as $val) {
            $close =  (!empty($val['close'])) ? $val['close'] : '0';
            $escalated =  (!empty($val['escalated'])) ? $val['escalated'] : '0';
            $wip =  (!empty($val['wip'])) ? $val['wip'] : '0';
            $new =  (!empty($val['new'])) ? $val['new'] : '0';
            $reject =  (!empty($val['reject'])) ? $val['reject'] : '0';
            $unassign =  (!empty($val['unassign'])) ? $val['unassign'] : '0';
            $frozen =  (!empty($val['frozen'])) ? $val['frozen'] : '0';
            $total = $close + $escalated + $wip + $new + $reject + $unassign + $frozen;
            ?>

            <tr>
                <td><?php echo (!empty($val['name'])) ? $val['name'] : ''; ?></td>
                <td><?php echo $new ?></td>
                <td><?php echo $escalated  ?></td>
                <td><?php echo $wip ?></td>
                <td><?php echo $close  ?></td>
                <td><?php echo $reject  ?></td>
                <td><?php echo $unassign  ?></td>
                <td><?php echo $frozen  ?></td>
                <td><?php echo $total; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
    </br>
    <hr class="hr-panel-heading" />
    </br>
    <?php echo $html ?>
    </br>

            <!-- <p class="text-center footer">In case of any queries, please contact us at <a href="mailto:info@a-pag.org">info@a-pag.org</a></p> -->

    </body>

</html>