<!DOCTYPE html>
<html>

<head>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta charset="utf-8">
    <title>ATR Summary</title>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel=" stylesheet" href="<?php echo base_url('assets/css/report-pdf.css?v='.time()) ?>">


</head>
<body>


<?php
$area = $GLOBALS['current_user']->area;
$role = $GLOBALS['current_user']->role;
$full_name = !empty($GLOBALS['current_user']->full_name) ? $GLOBALS['current_user']->full_name : '';
$role_name = !empty($GLOBALS['current_user']->role_name) ? $GLOBALS['current_user']->role_name : '';
$organisation = !empty($GLOBALS['current_user']->organisation) ? $GLOBALS['current_user']->organisation : '';
if (!empty($report_date)) {
    $summ =   _l('historical');
 } else{
    $summ =   _l('as_on_date');;
 }
?>
<table class=" header">
    <tr>
        <td class="text-left" width="75">
            <!-- <img src="<?php //echo //base_url('assets/images/cpcb-pdf-logo.png') ?>" alt=""> -->
            <?php if(!empty(get_logo('company_logo'))){ ?>
                <img src="<?php echo base_url(get_logo('company_logo')); ?>" alt="" style="width: 75px;height: 55px;">
            <?php } ?>
        </td>
        <td class="text-center">
            <h1><?php echo get_option('companyname'); ?></h1>

        </td>
        <td class="text-right" width="75">
            <?php if(!empty(get_area_logo())){ ?>
                <img src="<?php echo base_url(get_area_logo()); ?>" alt="" style="width: 75px;height: 55px;">
            <?php } ?>
        </td>
    </tr>
    </table>
    <table class="no-bdr">
        <tr>
            <td style="text-align:left;">
                <span class="date">Date: <?php echo date('d-m-Y H:i'); ?></span>
                <span class="generated">Generated by: <?php echo $full_name . ", " . $role_name. ", " . $organisation; ?></span>
                <span class="generated"><?php echo str_replace("/", ",", get_staff_location('plain')); ?></span>
                <span class="generated">In case of any queries, please contact support at <a href="mailto:<?php echo get_option('email_signature'); ?>"><?php echo get_option('email_signature'); ?></a></span>
            </td>
        </tr>
    </table>
    <h2 class="text-center">ATR Summary</h2>
     <span class="generated mB5"><?php echo $summ;  ?></span>
    </br>     
    <table class="">
<thead>
    <tr>
    <th  class="new"><?php echo _l('in_progress'); ?></th>
                                    <th  class="escalated"><?php echo _l('closed'); ?></th>
                                    <th  class="wip"><?php echo _l('total_reopen'); ?></th>
                                    <th  class="rejected"><?php echo _l('referred'); ?></th>
                                    <th  class="frozen"><?php echo _l('total_longterm'); ?></th>
                                    <?php if($role == 6 || $role == 9){ ?>
                                    <th  class="unassigned"><?php echo _l('unassign'); ?></th>
                                    <?php } ?>
                                    <th  class="frozen"><?php if($role==8){ echo _l('total_submitforapp'); }else{ echo _l('total_pendingforapp');} ?></th>
                                    <th  class="frozen"><?php echo _l('total_verified'); ?></th>
                                    <th  class="total-column"><?php echo _l('total'); ?></th>
    </tr>
</thead>
<tbody>
<?php foreach ($totals as $val) {
                                        //pre($val);
                                        $new = (!empty($val['new'])) ? $val['new'] : '0';
                                        $close = (!empty($val['close'])) ? $val['close'] : '0';
                                        $total_reopen = (!empty($val['reopen'])) ? $val['reopen'] : '0';
                                        $referred = (!empty($val['referred'])) ? $val['referred'] : '0';
                                        $total_longterm = (!empty($val['longterm'])) ? $val['longterm'] : '0';
                                        $unassign = (!empty($val['unassign'])) ? $val['unassign'] : '0';
                                        $pendingforapp = (!empty($val['total_pendingforapp'])) ? $val['total_pendingforapp'] : '0';
                                        $total_verified = (!empty($val['verified'])) ? $val['verified'] : '0';
                                        $total = $close + $total_reopen + $referred + $new + $total_longterm + $unassign + $pendingforapp + $total_verified;
                                        ?>

                                                <tr>
                                                    
                                                    <td ><?php echo $new ?></td>
                                                <td ><?php echo $close ?></td>
                                                <td ><?php echo $total_reopen ?></td>
                                                <td ><?php echo $referred ?></td>
                                                <td ><?php echo $total_longterm ?></td>
                                                <?php if($role == 6 || $role == 9){?>
                                                <td ><?php echo $unassign ?></td>
                                                <?php } ?>
                                                <td ><?php echo $pendingforapp ?></td>
                                                <td ><?php echo $total_verified ?></td>
                                                <td class="total_bold"><?php echo $total; ?></td>
                                                </tr>
                                    <?php } ?>
</tbody>
</table>
    <hr class="hr-panel-heading" />
    <table class="">

    <thead>
        <tr>
        <th ><?php echo _l('category_name'); ?></th>
                                <th class="dt_center_align"><?php echo _l('in_progress'); ?></th>
                                <th class="dt_center_align"><?php echo _l('closed'); ?></th>
                                <th class="dt_center_align"><?php echo _l('total_reopen'); ?></th>
                                <th class="dt_center_align"><?php echo _l('referred'); ?></th>
                                <th class="dt_center_align"><?php echo _l('total_longterm'); ?></th>
                                <?php if($role == 6 || $role == 9){?>
                                <th class="dt_center_align"><?php echo _l('unassign'); ?></th>
                                <?php } ?>
                                <th class="dt_center_align"><?php if($role== 8){ echo _l('total_submitforapp'); }else{ echo _l('total_pendingforapp');} ?></th>
                                <th class="dt_center_align"><?php echo _l('total_verified'); ?></th>
                                <th class="dt_center_align"><?php echo _l('total'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php
                                foreach ($statuses as $val) {
                                    $close = (!empty($val['close'])) ? $val['close'] : '0';
                                    $total_reopen = (!empty($val['reopen'])) ? $val['reopen'] : '0';
                                    $referred = (!empty($val['referred'])) ? $val['referred'] : '0';
                                    $new = (!empty($val['new'])) ? $val['new'] : '0';
                                    $total_longterm = (!empty($val['longterm'])) ? $val['longterm'] : '0';
                                    $unassign = (!empty($val['unassign'])) ? $val['unassign'] : '0';
                                    $pendingforapp = (!empty($val['total_pendingforapp'])) ? $val['total_pendingforapp'] : '0';
                                    $total_verified = (!empty($val['verified'])) ? $val['verified'] : '0';
                                    $total = $close + $total_reopen + $referred + $new + $total_longterm + $unassign + $pendingforapp + $total_verified;
                                    ?>

                                            <tr>
                                                <td><p class="ellipsis" data-toggle="tooltip" data-placement="top" title="<?php echo (!empty($val['name'])) ? strip_tags($val['name']) : '' ?>"><?php echo (!empty($val['name'])) ? mb_strimwidth($val['name'], 0, 40, '...') : '' ?></p></td>
                                                <td class="dt_center_align"><?php echo $new ?></td>
                                                <td class="dt_center_align"><?php echo $close ?></td>
                                                <td class="dt_center_align"><?php echo $total_reopen ?></td>
                                                <td class="dt_center_align"><?php echo $referred ?></td>
                                                <td class="dt_center_align"><?php echo $total_longterm ?></td>
                                                <?php if($role == 6 || $role == 9){?>
                                                <td class="dt_center_align"><?php echo $unassign ?></td>
                                                <?php } ?>
                                                <td class="dt_center_align"><?php echo $pendingforapp ?></td>
                                                <td class="dt_center_align"><?php echo $total_verified ?></td>
                                                <td class="total_bold dt_center_align"><?php echo $total; ?></td>
                                            </tr>
                                <?php } ?>
    </tbody>
</table>
    </br>
    <hr class="hr-panel-heading" />
    </br>
    <?php echo $html ?>
    </br>

            <!-- <p class="text-center footer">In case of any queries, please contact us at <a href="mailto:info@a-pag.org">info@a-pag.org</a></p> -->

    </body>

</html>